create table if not exists public.questionnaire2_participants (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  score integer not null,
  total_questions integer not null,
  duration_seconds integer,
  created_at timestamptz not null default now()
);
create table if not exists public.questionnaire2_answers (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  question_index integer not null,
  selected_answers jsonb not null default '[]'::jsonb,
  correct boolean not null,
  created_at timestamptz not null default now()
);
alter table public.questionnaire2_participants enable row level security;
alter table public.questionnaire2_answers enable row level security;
create policy "public insert questionnaire2 participants" on public.questionnaire2_participants for insert to anon with check (true);
create policy "public insert questionnaire2 answers" on public.questionnaire2_answers for insert to anon with check (true);
create policy "authenticated read questionnaire2 participants" on public.questionnaire2_participants for select to authenticated using (true);
create policy "authenticated read questionnaire2 answers" on public.questionnaire2_answers for select to authenticated using (true);
create policy "authenticated delete questionnaire2 participants" on public.questionnaire2_participants for delete to authenticated using (true);
create policy "authenticated delete questionnaire2 answers" on public.questionnaire2_answers for delete to authenticated using (true);